services:
  backend:
    image: ghcr.io/vatger/atciss/atciss-backend
    command: serve
    environment:
      ATCISS_REDIS_URL: redis://redis
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: ghcr.io/vatger/atciss/atciss-backend
    command: worker
    environment:
      ATCISS_REDIS_URL: redis://redis
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  scheduler:
    image: ghcr.io/vatger/atciss/atciss-backend
    command: scheduler
    restart: always
    environment:
      ATCISS_REDIS_URL: redis://redis
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgis/postgis:16-3.4-alpine@sha256:62f31fa40950df2a827fe793c26523887497903cd39e3ad6bfa342abbf1771e7
    volumes:
      - atciss-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [CMD, su, postgres, -c, pg_isready]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine@sha256:a40e29800d387e3cf9431902e1e7a362e4d819233d68ae39380532c3310091ac
    volumes:
      - atciss-redis-data:/data

    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  atciss-db-data:
  atciss-redis-data:
