services:
  backend:
    image: atciss-backend-local
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    environment:
      ATCISS_DATABASE_DSN: "postgresql+asyncpg://postgres:fnord@db/atciss"
      ATCISS_DEBUG_SQL: 0
    volumes:
      - ./atciss:/code/atciss
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini

  worker:
    image: atciss-backend-local
    ports:
      - "9000:9000"
    environment:
      ATCISS_DATABASE_DSN: "postgresql+asyncpg://postgres:fnord@db/atciss"
      ATCISS_DEBUG_SQL: 0
    volumes:
      - ./atciss:/code/atciss
      - ./contrib:/code/contrib
    # ensure current atciss-backend-local image is used
    depends_on:
      - backend

  scheduler:
    image: atciss-backend-local
    volumes:
      - ./atciss:/code/atciss
    # ensure current atciss-backend-local image is used
    depends_on:
      - backend

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fnord
      - POSTGRES_DB=atciss
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
