services:
  backend:
    image: atciss-backend
    build:
      context: .
      target: dev
    entrypoint:
      - "uvicorn"
      - "atciss.app.asgi:get_application"
      - "--factory"
      - "--reload"
      - "--reload-dir=/code/atciss"
      - "--log-level=info"
    ports:
      - "8000:8000"
    environment:
      ATCISS_DATABASE_DSN: "postgresql+asyncpg://postgres:fnord@db/atciss"
      ATCISS_REDIS_HOST: redis
    volumes:
      - ./atciss:/code/atciss

  worker:
    image: atciss-backend
    build:
      context: .
      target: dev
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "worker"
      - "--loglevel=info"
    environment:
      ATCISS_REDIS_HOST: redis
    volumes:
      - ./atciss:/code/atciss
    depends_on:
      - redis

  beat:
    image: atciss-backend
    build:
      context: .
      target: dev
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "beat"
      - "--loglevel=info"
    environment:
      ATCISS_REDIS_HOST: redis
    volumes:
      - ./atciss:/code/atciss
    depends_on:
      - redis

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - atciss-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fnord
      - POSTGRES_DB=atciss
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    volumes:
      - atciss-redis-data:/data

volumes:
  atciss-db-data:
  atciss-redis-data:
