services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      ATCISS_BIND: "[::]:8000"
      ATCISS_REDIS_HOST: redis
      ATCISS_RELOAD: true
    volumes:
      - ./atciss:/code/atciss

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - atciss-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fnord
      - POSTGRES_DB=atciss
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    volumes:
      - atciss-redis-data:/data

volumes:
  atciss-db-data:
  atciss-redis-data:
