services:
  backend:
    image: ghcr.io/vatger/atciss/atciss-backend
    entrypoint:
      - "atciss"
      - "serve"
    environment:
      ATCISS_REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: ghcr.io/vatger/atciss/atciss-backend
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "worker"
    environment:
      ATCISS_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  beat:
    image: ghcr.io/vatger/atciss/atciss-backend
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "beat"
      - "--schedule=/beat/celerybeat-schedule"
    environment:
      ATCISS_REDIS_HOST: redis
    volumes:
      - atciss-beat:/beat
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgis/postgis:16-3.4-alpine@sha256:a07012c92745d8f21e6cf33d846467076cfb167340750cf37c3329991f25da34
    volumes:
      - atciss-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine@sha256:fd5de2340bc46cbc2241975ab027797c350dec6fd86349e3ac384e3a41be6fee
    volumes:
      - atciss-redis-data:/data

    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  atciss-db-data:
  atciss-redis-data:
  atciss-beat:
