services:
  backend:
    env_file:
      - stack.env

  worker:
    env_file:
      - stack.env

  scheduler:
    env_file:
      - stack.env

  db:
    env_file:
      - stack.env

  redis: {}

  frontend:
    image: ghcr.io/vatger/atciss/atciss-frontend
    volumes:
      - atciss-static-files:/srv/atciss-static:ro
    ports:
      - "8011:80"
    depends_on:
      - backend
