services:
  backend:
    build:
      context: .
      target: dev
    entrypoint:
      - python
      - -m
      - atciss.cli.cli
      - serve
    ports:
      - "8000:8000"
    environment:
      ATCISS_DATABASE_DSN: "postgresql+asyncpg://postgres:fnord@db/atciss"
    volumes:
      - ./atciss:/code/atciss
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini

  worker:
    build:
      context: .
      target: dev
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "worker"
      - "--loglevel=info"
    environment:
      ATCISS_DATABASE_DSN: "postgresql+asyncpg://postgres:fnord@db/atciss"
    volumes:
      - ./atciss:/code/atciss
      - ./contrib:/code/contrib

  beat:
    build:
      context: .
      target: dev
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "beat"
      - "--schedule=/tmp/celerybeat-schedule"
      - "--loglevel=info"
    volumes:
      - ./atciss:/code/atciss

  db:
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fnord
      - POSTGRES_DB=atciss
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
