services:
  backend:
    image: atciss-backend
    entrypoint:
      - "uvicorn"
      - "atciss.app.asgi:get_application"
      - "--factory"
      - "--host=0.0.0.0"
    environment:
      ATCISS_REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy

  worker:
    image: atciss-backend
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "worker"
    environment:
      ATCISS_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  beat:
    image: atciss-backend
    entrypoint:
      - "celery"
      - "-A"
      - "atciss"
      - "beat"
      - "--schedule=/tmp/celerybeat-schedule"
    environment:
      ATCISS_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - atciss-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [CMD, pg_isready]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine
    volumes:
      - atciss-redis-data:/data

    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  atciss-db-data:
  atciss-redis-data:
