[tool.poetry]
name = "atciss"
version = "0.1.0"
description = "VATSIM Germany ATCISS"
authors = ["Franz Pletz <fpletz@fnordicwalking.de>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/a3li/atciss"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.101"
uvicorn = {extras = ["standard"], version = "^0.23"}
click = "^8.1"
gunicorn = "^21.2"
aiohttp = "^3.8.4"
redis = "^5.0.0"
beautifulsoup4 = "^4.12.2"
pynotam = { git = "https://github.com/globin/PyNotam", rev = "84b741863d09aaa616e6f378a2e6e5eab8df706f" }
metar = "^1.11.0"
pydantic = "^2"
pydantic-settings = "^2.0.2"

[tool.poetry.group.dev.dependencies]
black = "^23.1"
mypy = "^1.0"
flake8 = "^6.0"
flake8-import-order = "^0.18"
flake8-docstrings = "^1.7"
types-beautifulsoup4 = "^4.12.0.5"

[tool.poetry.scripts]
atciss = 'atciss.cli:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = [
  "atciss/config/gunicorn.py"
]
python_version = '3.10'
show_error_codes = true
follow_imports = 'silent'
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_unused_configs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true
implicit_optional = true

[[tool.mypy.overrides]]
module = [
    "gunicorn.*",
    "redis.*",
]
ignore_missing_imports = true
